create table account_identities (
    id bigint generated by default as identity primary key,
    user_account_id bigint not null references user_accounts(id),
    provider varchar(50) not null,
    provider_user_key varchar(255) not null,
    secret_hash varchar(255),
    external_username varchar(255),
    external_chat_id varchar(255),
    verified_at timestamp with time zone,
    created_at timestamp with time zone not null,
    last_seen_at timestamp with time zone,
    constraint uk_account_identities_provider_user_key unique (provider, provider_user_key),
    constraint uk_account_identities_user_provider unique (user_account_id, provider)
);

create index idx_account_identities_user_account on account_identities (user_account_id);

insert into account_identities (
    user_account_id,
    provider,
    provider_user_key,
    external_username,
    external_chat_id,
    verified_at,
    created_at,
    last_seen_at
)
select
    ti.user_account_id,
    'telegram',
    ti.telegram_user_id,
    ti.telegram_username,
    ti.private_chat_id,
    ti.created_at,
    ti.created_at,
    ti.last_seen_at
from telegram_identities ti
where not exists (
    select 1
    from account_identities ai
    where ai.provider = 'telegram'
      and ai.provider_user_key = ti.telegram_user_id
);

create table link_tokens (
    id bigint generated by default as identity primary key,
    user_account_id bigint not null references user_accounts(id),
    provider varchar(50) not null,
    token_hash varchar(128) not null,
    token_prefix varchar(20) not null,
    expires_at timestamp with time zone not null,
    consumed_at timestamp with time zone,
    created_at timestamp with time zone not null,
    constraint uk_link_tokens_token_hash unique (token_hash)
);

create index idx_link_tokens_user_provider on link_tokens (user_account_id, provider);
