create table tdlight_connections (
    id bigint generated by default as identity primary key,
    user_account_id bigint not null references user_accounts(id),
    status varchar(50) not null,
    phone_mask varchar(50),
    tdlight_user_id varchar(255),
    encrypted_session_blob text,
    encrypted_session_key_version varchar(100),
    created_at timestamp with time zone not null,
    verified_at timestamp with time zone,
    revoked_at timestamp with time zone,
    last_synced_at timestamp with time zone
);

create index idx_tdlight_connections_user_account on tdlight_connections (user_account_id, created_at);
create index idx_tdlight_connections_status on tdlight_connections (status, created_at);

create table channel_migrations (
    id bigint generated by default as identity primary key,
    initiated_by_user_id bigint not null references user_accounts(id),
    tdlight_connection_id bigint not null references tdlight_connections(id),
    target_conversation_id bigint references conversations(id),
    source_channel_id varchar(255) not null,
    source_channel_handle varchar(255),
    status varchar(50) not null,
    activated_at timestamp with time zone not null,
    last_seen_remote_message_id varchar(255),
    imported_message_count integer not null default 0,
    imported_media_count integer not null default 0,
    last_error text,
    retention_until timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_channel_migrations_initiated_by on channel_migrations (initiated_by_user_id, created_at);
create index idx_channel_migrations_status on channel_migrations (status, created_at);
create index idx_channel_migrations_source_channel on channel_migrations (source_channel_id, created_at);

alter table conversation_messages
    add column imported_via varchar(50);

alter table conversation_messages
    add column expires_at timestamp with time zone;

alter table conversation_attachments
    add column imported_via varchar(50);

alter table conversation_attachments
    add column expires_at timestamp with time zone;
