create table tdlight_session_bindings (
    id bigint generated by default as identity primary key,
    tdlight_connection_id bigint not null references tdlight_connections(id),
    session_key varchar(255) not null,
    database_directory varchar(1000) not null,
    files_directory varchar(1000) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    last_opened_at timestamp with time zone,
    revoked_at timestamp with time zone
);

create unique index uq_tdlight_session_bindings_connection_active
    on tdlight_session_bindings (tdlight_connection_id, revoked_at);

create unique index uq_tdlight_session_bindings_session_key
    on tdlight_session_bindings (session_key);

create table tdlight_session_secrets (
    id bigint generated by default as identity primary key,
    tdlight_connection_id bigint not null references tdlight_connections(id),
    session_binding_id bigint not null references tdlight_session_bindings(id),
    session_key varchar(255) not null,
    encrypted_session_blob text not null,
    encryption_key_version varchar(100) not null,
    session_fingerprint varchar(255),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    revoked_at timestamp with time zone
);

create index idx_tdlight_session_secrets_connection_updated
    on tdlight_session_secrets (tdlight_connection_id, updated_at);

create index idx_tdlight_session_secrets_binding_updated
    on tdlight_session_secrets (session_binding_id, updated_at);
