create table conversations (
    id bigint generated by default as identity primary key,
    tenant_key varchar(100) not null,
    title varchar(200) not null,
    created_at timestamp with time zone not null
);

create index idx_conversations_tenant_key on conversations (tenant_key);

create table transport_bindings (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null references conversations(id),
    transport varchar(30) not null,
    external_chat_id varchar(255) not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    constraint uk_transport_binding unique (conversation_id, transport, external_chat_id)
);

create index idx_transport_bindings_lookup on transport_bindings (transport, external_chat_id, active);

create table conversation_messages (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null references conversations(id),
    source_transport varchar(30) not null,
    source_chat_id varchar(255),
    source_message_id varchar(255),
    author_external_id varchar(255),
    author_display_name varchar(255) not null,
    body text not null,
    created_at timestamp with time zone not null
);

create unique index uk_message_source on conversation_messages (source_transport, source_chat_id, source_message_id);
create index idx_conversation_messages_created on conversation_messages (conversation_id, created_at);

create table delivery_records (
    id bigint generated by default as identity primary key,
    conversation_message_id bigint not null references conversation_messages(id),
    target_transport varchar(30) not null,
    target_chat_id varchar(255) not null,
    target_message_id varchar(255) not null,
    delivered_at timestamp with time zone not null,
    constraint uk_delivery_record unique (conversation_message_id, target_transport, target_chat_id)
);

create table sync_cursors (
    cursor_key varchar(100) primary key,
    next_offset bigint not null
);
