create table user_accounts (
    id bigint generated by default as identity primary key,
    tenant_key varchar(100) not null,
    username varchar(100) not null,
    display_name varchar(255) not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    constraint uk_user_accounts_username unique (username)
);

create index idx_user_accounts_tenant_key on user_accounts (tenant_key);

create table telegram_identities (
    id bigint generated by default as identity primary key,
    user_account_id bigint not null references user_accounts(id),
    telegram_user_id varchar(255) not null,
    telegram_username varchar(255),
    private_chat_id varchar(255) not null,
    created_at timestamp with time zone not null,
    last_seen_at timestamp with time zone not null,
    constraint uk_telegram_identities_user_account unique (user_account_id),
    constraint uk_telegram_identities_telegram_user_id unique (telegram_user_id)
);

create table api_tokens (
    id bigint generated by default as identity primary key,
    user_account_id bigint not null references user_accounts(id),
    token_hash varchar(128) not null,
    token_prefix varchar(20) not null,
    label varchar(100) not null,
    revoked boolean not null,
    expires_at timestamp with time zone,
    created_at timestamp with time zone not null,
    last_used_at timestamp with time zone,
    constraint uk_api_tokens_token_hash unique (token_hash)
);

create index idx_api_tokens_user_account on api_tokens (user_account_id, revoked);

alter table conversation_messages
    add column author_user_id bigint references user_accounts(id);

create index idx_conversation_messages_author_user_id on conversation_messages (author_user_id);
