create table conversation_members (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null references conversations(id),
    user_account_id bigint not null references user_accounts(id),
    invited_by_user_id bigint references user_accounts(id),
    role varchar(30) not null,
    joined_at timestamp with time zone not null,
    constraint uk_conversation_member unique (conversation_id, user_account_id)
);

create index idx_conversation_members_user_account on conversation_members (user_account_id, joined_at);
create index idx_conversation_members_conversation on conversation_members (conversation_id, joined_at);

create table conversation_invites (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null references conversations(id),
    created_by_user_id bigint not null references user_accounts(id),
    accepted_by_user_id bigint references user_accounts(id),
    invite_hash varchar(128) not null,
    invite_prefix varchar(20) not null,
    revoked boolean not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone,
    accepted_at timestamp with time zone,
    constraint uk_conversation_invites_hash unique (invite_hash)
);

create index idx_conversation_invites_conversation on conversation_invites (conversation_id, created_at);
