create table conversation_attachments (
    id bigint generated by default as identity primary key,
    conversation_message_id bigint not null references conversation_messages(id),
    attachment_kind varchar(30) not null,
    original_filename varchar(255) not null,
    mime_type varchar(255) not null,
    size_bytes bigint not null,
    storage_key varchar(500) not null,
    created_at timestamp with time zone not null
);

create index idx_conversation_attachments_message on conversation_attachments (conversation_message_id, id);
